config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :companies do

  end

  resources :jobs
root 'companies#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base

  belongs_to :company

  validates :title, presence: true
  validates :company, presence: true
  validates :url, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_action :authenticate_user!

  def index
  @companies = Company.page(params[:page]).per(25)
  end

  def new
  Rails.logger.debug "AA::"
  @company = Company.new
  Rails.logger.debug "BB::"
  end
  def show
  end
  def create
    @company = Company.new(params.require(:company).permit(:name, :company_type))
    if @company.save
      redirect_to root_path
    else
      render "new"
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :authenticate_user!

  def index
  @jobs = Job.page(params[:page]).per(25)
  end

  def new
    @job = Job.new
  end

  def create

    @job = Job.new(params.require(:job).permit(:title, :company_id, :url, :location, :job_type))
    if @job.save
      redirect_to jobs_path
    else
      render "new"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/companies/index.html.erb
<<<<<<< HEAD
<div class="row" style="margin-top:100px;">
  <div class = "col-md-2">
    <button type="button" class="btn"><%= link_to "Add a company", new_company_path %></button>
  </div>
  <div class = "col-md-2 col-md-offset-3">
    <h1>Companies</h1>
    <% @companies.each_with_index do |company, index| %>
      <div class="job">
        <h2><%= index+1 %> <%= "#{company.name} (#{company.company_type})" %></h2>
      </div>
    <% end %>
    <p><%= paginate @companies %></p>
  </div>
  <div class = "col-md-2 pull-right">
    <button type="button" class="btn"><%= link_to "Add a job", new_job_path %></button>
=======
</br></br></br>
<div class="row">
<h1>Companies (<%= link_to "Add a company", new_company_path %> )</h1>
<table>
  <thead>
    <th>Name</th>
    <th>Type</th>
    <th>Action</th>
  </thead>
  <tbody style="border:1px solid black">
  <% @companies.each_with_index do |company, index| %>
    <tr>
      <td style="border:1px dotted black;padding: 10px;margin: 5px">
        <a type="button" data-toggle="modal" data-target="#jobs-<%=index%>">
          <%= "#{company.name}"%>
        </a>
      </td>
      <td style="border:1px dotted black;padding: 10px;margin: 5px"><%= "#{company.company_type}"%></td>
      <td style="border:1px dotted black;padding: 10px;margin: 5px"><%= link_to "Add a job", new_job_path %></td>
    </tr>

<!-- Modal -->
<div class="modal fade" id="jobs-<%=index%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Jobs in <%= company.name%> (<%= company.jobs.count%>)</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% unless company.jobs.present? %>
          No Jobs yet
        <% else %>
          <ul>
          <% company.jobs.each_with_index do |job, index|%>
            <li> <%= job.title%> </li>
          <% end %>
          </ul>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
>>>>>>> 1398d23d420b0d76d5a4e71c251610fac9f8b02d
  </div>
</div>

  <%end%>
  </tbody>
  <p><%= paginate @companies %></p>
</table>
</div>

app/views/companies/new.html.erb
<div class="row" style="margin-top:100px;">
  <div class = "col-md-6 col-md-offset-3">
    <div class = "panel panel-success">
      <div class = "panel-heading">Add a company</div>
      <div class = "panel-body">
<%= simple_form_for @company do |form| %>
  <%= form.input :name, label: "Name" %>
  <%= form.input :company_type, label: "Type" %>
  <%= form.button :submit %>
<% end %>
</div>
</div>
 </div>
</div>

app/views/jobs/index.html.erb
<div class="row" style="margin-top:100px;">
<h1>Jobs</h1>
<% @jobs.each_with_index do |job, index| %>
  <div style ="border:1px solid blue; text-align:center;">
    <h3><%= index+1 %> <%= link_to job.title, job.url %> (<%= job.company.name%>)</h3>
    <h5>Job Type: <%= job.company.company_type %></h5>
  </div>
<% end %>
<p><%= paginate @jobs %></p>
</div>

app/views/jobs/new.html.erb
<div class="row" style="margin-top:100px;">
  <div class = "col-md-6 col-md-offset-3">
    <div class = "panel panel-primary">
      <div class = "panel-heading">Add A Job</div>
      <div class = "panel-body">
<%= simple_form_for @job do |form| %>
  <%= form.input :title, label: "Job title" %>
  <%= form.association :company, label: "Your company" %>
  <%= form.input :job_type, label: "Job Type" %>
  <%= form.input :location, label: "Location" %>
  <%= form.input :url, label: "Link to job" %>
  <%= form.button :submit %>
<% end %>
</div>
</div>
</div>
</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   Job Portal
    by Aquil Hussain</a>
  </small>
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <!-- <p><%= link_to "Job portal", '#', id: "logo" %></p> -->
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to image_tag("Logo.png", alt: "Job logo"), companies_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   companies_path %></li>
        <% if user_signed_in? %>
        <li class="bg-master-light-1">
            <a href="<%=destroy_user_session_path%>" data-method="delete" method="delete" class="clearfix">
              <span class="pull-left">logout</span>
              <span class="pull-right"><i class="pg-power"></i></span>
            </a>
          </li>
        <% else %>
          <li><%= link_to "Sign in",   '#' %></li>
          <li><%= link_to "sign up",   '#' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobPortal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container" style="background-color:#ccc">
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>